"""Owner-facing A3 key-pose and effect player, built from portable local assets."""
import json
import math
import html
from PIL import Image, ImageDraw
from common import ART, ROOT, read, write, sha, relative
from board import font
from figures import OUT, paste_frame
from generate import Budget


def build():
    m=read(OUT/'figures.json');effects=read(OUT/'effects.json');roster=read(ART/'a3-roster-v1.json')['entities']
    review=ART/'review/a3';review.mkdir(exist_ok=True)
    frames=m['frames'];contact=Image.new('RGBA',(1600,100+len(roster)*170),'#eee0bd');d=ImageDraw.Draw(contact)
    d.text((24,16),'A3 / KEY POSES / 1080p NEAR SCALE',font=font(27,True),fill='#38261f')
    d.text((24,58),'Generated anatomy. Extracted alpha. Run pairs may repeat; no eight-direction or finished animation claim.',font=font(19),fill='#38261f')
    for n,e in enumerate(roster):
        y=100+n*170;d.text((24,y+25),e['name'],font=font(19,True),fill='#38261f')
        rows=[r for r in frames if r['entity']==e['id']]
        if not rows:d.text((330,y+70),'MISSING — spending latch; no generated source',font=font(19),fill='#742d36')
        for k,r in enumerate(rows):
            x=330+k*157;paste_frame(contact,r,(x,y+105),64.8)
            d.text((x-54,y+124),r['state'],font=font(14),fill='#38261f')
    contact.convert('RGB').save(review/'key-pose-contact.png')
    data={'figures':m,'effects':effects,'roster':roster,'budget':Budget().summary(),'stop':read(ART/'waves/A3/stop-report.json')}
    data['local_diagnostics']=[{'artifact':p.stem,'verdict':read(p)['verdict'],'codes':read(p)['codes'],
        'observation':read(p).get('answers',{}).get('observation','ungraded')} for p in sorted((ART/'grades').glob('ui-a3-*.json'))]
    # File URLs need no fetch: metadata is embedded, image links stay project-relative.
    for r in data['figures']['frames']:r['url']='../../../'+r['file']
    for r in data['effects']['exports']:r['url']='../../../'+r['file']
    doc=HTML.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('</','<\\/'))
    (review/'owner.html').write_text(doc,encoding='utf-8')
    write(ART/'waves/A3/links.json',[{'label':'Owner board / pose player','href':'owner.html'},
        {'label':'Native key-pose contact','href':'key-pose-contact.png'},
        {'label':'1080p composite','href':'../../delivery/a3/proofs/open-oval-1920x1080.png'},
        {'label':'1440p composite','href':'../../delivery/a3/proofs/open-oval-2560x1440.png'},
        {'label':'Effect sheet','href':'../../delivery/a3/effects-contact.png'}])
    (ART/'waves/A3/board-note.txt').write_text('PARTIAL: spending latched at cinder-hound injury after HTTP 400 content-moderated/no file. 37 charged calls, 36 saved sources. Mire maw, thornback, hush moth and hound hit/death missing. Three mage absorb bodies reuse cast poses. Five source rejects remain visible; explicitly reviewed individual subframes can be salvaged without accepting their source sheet. Full A3 completion gate remains failed. Owner board shows available assets and gaps.',encoding='utf-8')
    print(json.dumps({'owner_board':relative(review/'owner.html'),'frames':len(frames),'effects':len(effects['recipes'])}))


HTML=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mage Arena — A3 owner board</title>
<style>
:root{color-scheme:light;--ink:#38261f;--paper:#eee0bd;--blue:#226b8b}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.55 Georgia,serif}header{background:#202923;color:#f3e6c5;padding:32px max(24px,calc((100% - 1440px)/2))}h1{font-size:clamp(32px,5vw,58px);line-height:1.1;margin:12px 0}header p{max-width:950px;color:#d1c6a4}main{max-width:1488px;margin:auto;padding:24px}nav{display:flex;flex-wrap:wrap;gap:14px}a{color:var(--blue)}header a{color:#a6d9da}.eyebrow{letter-spacing:.15em;font:13px Arial,sans-serif}section{margin:28px 0 44px}h2{font-size:28px;border-bottom:2px solid #9a7152;padding-bottom:8px}.controls{display:flex;flex-wrap:wrap;gap:14px;align-items:end}label{display:grid;gap:3px;font:14px Arial,sans-serif}select,button{padding:9px;font:16px Arial,sans-serif;border:1px solid #8c8065;background:#f9edce;color:var(--ink);border-radius:3px}button{cursor:pointer}canvas{display:block;width:100%;height:420px;border:1px solid #9a7152;margin:18px 0;background:#d8cdae}.note{padding:14px 18px;border-left:4px solid var(--blue);background:#f6ebce}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,330px),1fr));gap:20px}.card{background:#f6ebce;padding:18px;border-top:4px solid #9a7152}.card h3{margin:0 0 10px}.card img{max-width:100%;height:auto}.portrait{width:70px;float:right;margin:0 0 8px 8px}.poses{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.pose{font:12px Arial,sans-serif;text-align:center}.pose img{width:100%;height:90px;object-fit:contain;background:#d5c8a6}.wide{max-width:100%;height:auto}details{margin:14px 0}summary{cursor:pointer;font-weight:bold}table{border-collapse:collapse;width:100%;font:14px Arial,sans-serif}th,td{text-align:left;padding:8px;border-bottom:1px solid #c6b897;overflow-wrap:anywhere}.table-wrap{overflow:auto}footer{padding:24px;background:#202923;color:#f3e6c5}#status{font:14px Arial,sans-serif}.pill{font:12px Arial,sans-serif;letter-spacing:.08em;color:#73523d}.links{display:flex;gap:18px;flex-wrap:wrap}
</style><header><div class="eyebrow">MAGE ARENA / ART A3 / OWNER REVIEW</div><h1>Figures in the open oval</h1><p>Tessera &amp; Lime, the confirmed near camera, and an oblique view with a 55° target. Four mages, five available enemy designs, three missing enemy designs, and exact authored combat cues. These are review candidates, with their construction and remaining limits visible.</p><nav><a href="index.html">Every generated attempt</a><a href="key-pose-contact.png">Native pose contact</a><a href="../../delivery/a3/effects-contact.png">Effects contact</a><a href="../../delivery/a3/figures.json">Figure manifest</a><a href="../../delivery/a3/effects.json">Effect manifest</a><a href="../../../docs/waves/A3-figures-and-effects.md">Design / evidence</a></nav></header><main>
<p class="note" id="spend"></p><p class="note"><strong>A3 INCOMPLETE: SPENDING LATCHED.</strong> The provider returned HTTP 400 content-moderated and no image for cinder-hound injury. No further paid calls or correction attempts were made. Three creature designs and hound hit/death are missing; animation and costume corrections remain pending. Five rejected sheets are retained. Selected isolated subframes are salvaged with explicit crop records.</p><section><h2>Native-scale pose and timing study</h2><div class="controls"><label>Figure<select id="entity"></select></label><label>Pose<select id="state"><option>idle</option><option>run</option><option>cast</option><option>absorb</option><option>hit</option><option>death</option><option>attack</option></select></label><label>Resolution basis<select id="resolution"><option value="1080">1080p</option><option value="1440">1440p</option></select></label><label>Distance<select id="distance"><option value="near">Near · 6%</option><option value="standard">Standard · 5%</option><option value="far">Far · 4%</option></select></label><label>Surface<select id="surface"><option value="arena">Chosen arena source</option><option value="light">Chalk</option><option value="dark">Umber</option></select></label><label>Effect<select id="effect"></select></label><button id="play">Play study</button></div><canvas id="stage" aria-label="Native-size figure and effect preview"></canvas><p id="status"></p><p class="note">Run preview uses one generated run key with a procedural 1.5 px bob; paired samples are available below, but repetition or mirroring is not presented as a finished gait. Cast and attack can switch between two generated poses. Idle/absorb breathe procedurally. Death holds its generated fallen key. Timing is illustrative and is not combat data. Upright bodies are never rotated to fake another camera direction.</p></section>
<section><h2>Full-resolution composition proofs</h2><p>Open at 100% to judge the actual 43.2–64.8 px body range at 1080p and 57.6–86.4 px at 1440p. The chosen background retains all its painted figures and effects. Added sprites, labels and exact arcs are separate composite layers. Numerical 55° is the projection target; the generator's exact anatomical elevation is not measured.</p><div class="links"><a href="../../delivery/a3/proofs/open-oval-1920x1080.png">1920 × 1080 proof</a><a href="../../delivery/a3/proofs/open-oval-2560x1440.png">2560 × 1440 proof</a><a href="../../delivery/a3/proofs/encounter-1920x1080.png">1080p enemy encounter</a><a href="../../delivery/a3/proofs/encounter-2560x1440.png">1440p enemy encounter</a></div><a href="../../delivery/a3/proofs/open-oval-1920x1080.png"><img class="wide" src="../../delivery/a3/proofs/open-oval-1920x1080.png" alt="Figure-over-open-oval scale proof"></a></section>
<section><h2>The four mages and enemy roster</h2><p>All six mage states have review exports; Brennic, Garran and Iskar absorb reuse their casting bodies. Mire maw, thornback, hush moth and cinder-hound hit/death are MISSING after the spending stop. Soldier and creature attacks use their baseline attack poses; they have no magical absorb or player cast ability. AI mages reuse the school atlases. Echo is excluded by the current season plan. Fallen art can represent defeat; ordinary arena losses are not automatically lethal.</p><div class="grid" id="roster"></div></section>
<section><h2>Combat effects</h2><p>Every effect is authored geometry, with four presentation phases in transparent sheets at all three distances and both resolutions. The 140° absorb is projected onto the ground with 220° behind it open. Perfect absorb adds a contact flash, not a surrounding bubble. Shapes separate magic, steel and unblockable threats. Raster sheets face right; other headings must rotate the world geometry before projection.</p><img class="wide" src="../../delivery/a3/effects-contact.png" alt="All authored effect families"><details><summary>Water spell mapping and integration limits</summary><p>These are family motifs. The 24 CSV rows retain their own shapes, timing and branches; a motif does not implement a fan, decoy, grab, or full tier animation. Fire, Earth and Air have generic bolt/line looks pending W8. Net 2.5 m is ambiguous in the baseline; the review recipe treats it as diameter and requires integration resolution.</p><div class="table-wrap"><table><thead><tr><th>Line / tier</th><th>Spell</th><th>Shape authority</th><th>Family motif</th></tr></thead><tbody id="mappings"></tbody></table></div></details></section>
<section><h2>Local diagnostics remain advisory</h2><p>The pose-contact framing field was rejected even though its accompanying prose describes the grid as readable. The rejection remains unresolved; global UI acceptance checks fail. No automated opinion is owner acceptance.</p><div id="diagnostics"></div></section><section><h2>Construction and remaining review</h2><p>Generated: original figures and distinct pose drawings where the source achieved them. Derived: magenta removal, antialiased edge cleanup, crops, uniform scale, ground anchors and atlases; any horizontal flip is recorded per frame. Procedural: all effect geometry and preview motion. Composited: figures/effects over the chosen source. The text-only guarded generator does not condition on portrait image bytes, so garment, face and facing drift remain visible in the sources.</p><p>The local grader can reject or route to the owner. Passing export and browser checks cannot accept art, certify precise generated camera elevation, or establish combat readability in motion. Owner taste, final identity continuity, engine playback, other facings and full animation remain unmeasured.</p></section></main><footer>Original project designs. Review candidates only. No model acceptance. No game-engine performance claim.</footer>
<script>const DATA=__DATA__;
const $=id=>document.getElementById(id),images=new Map();let playing=false,start=0;
function img(url){if(!images.has(url)){let i=new Image();i.src=url;images.set(url,i)}return images.get(url)}
DATA.figures.frames.forEach(r=>img(r.url));DATA.effects.exports.forEach(r=>img(r.url));const arena=img('../sources/01-tessera-open-oval-sparse-near-a01.jpg');
$('spend').textContent=`This session: ${DATA.budget.wave_reserved-89} charged image calls. Project: ${DATA.budget.wave_reserved} / 180; ${DATA.budget.hard_remaining} remaining. Shared-account allowance is not measured. Generated sources remain owner-review only.`;
for(const e of DATA.roster){$('entity').add(new Option(e.name,e.id));const rows=DATA.figures.frames.filter(r=>r.entity===e.id);let a=document.createElement('article');a.className='card';a.innerHTML=`${e.portrait?`<img class="portrait" src="../../../${e.portrait}" alt="${e.name} portrait reference">`:''}<div class="pill">${e.kind==='mage'?e.school.toUpperCase():e.kind.toUpperCase()}</div><h3>${e.name}</h3><p>${rows.length} pose exports (including disclosed reuse) · ${rows.length?`<a href="../../delivery/a3/atlases/${e.id}.png">transparent atlas</a>`:`MISSING: spending stopped`}</p><div class="poses">${rows.map(r=>`<div class="pose"><a href="${r.url}"><img src="${r.url}" alt="${e.name} ${r.state}"></a>${r.state}${r.derivation?' ? cast reuse':''}${r.horizontal_flip?' · flipped':''}</div>`).join('')}</div><details><summary>Identity and limits</summary><p>${e.design}</p><p>One camera-facing study; run samples may repeat. View the attempt archive for direct source observations and local diagnostics.</p></details>`;$('roster').append(a)}
$('effect').add(new Option('None','none'));for(const e of DATA.effects.recipes)$('effect').add(new Option(e.id,e.id));$('effect').value='water-absorb';
$('mappings').innerHTML=DATA.effects.water_mappings.map(r=>`<tr><td>${r.line} / ${r.tier}${r.branch}</td><td>${r.name}</td><td>${r.shape_authority}</td><td>${r.family_motif}</td></tr>`).join('');
$('diagnostics').innerHTML=DATA.local_diagnostics.map(r=>`<details><summary>${r.artifact}: ${r.verdict} (${r.codes.join(', ')})</summary><p>${r.observation}</p></details>`).join('');
function render(t){const canvas=$('stage'),ctx=canvas.getContext('2d');const width=Math.round(canvas.clientWidth);if(canvas.width!==width){canvas.width=width;canvas.height=420}const w=canvas.width,h=canvas.height;ctx.fillStyle=$('surface').value==='dark'?'#38261f':'#ddd0ad';ctx.fillRect(0,0,w,h);if($('surface').value==='arena'&&arena.complete&&arena.naturalWidth){let k=Math.max(w/arena.naturalWidth,h/arena.naturalHeight);ctx.drawImage(arena,(w-arena.naturalWidth*k)/2,(h-arena.naturalHeight*k)/2,arena.naturalWidth*k,arena.naturalHeight*k);}let e=$('entity').value,state=$('state').value,rs=+$('resolution').value/1080,d=$('distance').value,frac={near:.06,standard:.05,far:.04}[d],body=1080*rs*frac,foot=[w*.3,h*.64];let key=state;
if(state==='run')key='run-a';if(state==='cast')key=playing&&Math.floor((t-start)/250)%2?'cast-release':'cast-windup';if(state==='attack')key=playing&&Math.floor((t-start)/250)%2?'attack-release':'attack-windup';let row=DATA.figures.frames.find(r=>r.entity===e&&r.state===key);
let eff=DATA.effects.exports.find(r=>r.id===$('effect').value&&r.viewport_height===1080*rs&&r.distance===d);if(eff){let i=img(eff.url),n=playing?Math.floor((t-start)/100)%4:1,[ew,eh]=eff.frame_size;if(i.complete&&i.naturalWidth)ctx.drawImage(i,n*ew,0,ew,eh,foot[0]-ew/2,foot[1]-eh/2,ew,eh)}
if(row){let i=img(row.url),s=body/192;let bob=playing&&['idle','run','absorb'].includes(state)?Math.sin((t-start)/(state==='run'?80:350))*1.5*rs:0;ctx.fillStyle='rgba(56,38,31,.18)';ctx.beginPath();ctx.ellipse(...foot,body*.2,body*.07,0,0,Math.PI*2);ctx.fill();if(i.complete&&i.naturalWidth)ctx.drawImage(i,foot[0]-256*s,foot[1]-320*s+bob,512*s,384*s);$('status').textContent=`${e} / ${key} · nominal human body ${body.toFixed(1)} px · ${d} / ${1080*rs}p · ${playing?'procedural timing preview':'held key pose'} · ${row.horizontal_flip?'recorded horizontal correction; handedness flips':'source orientation retained'}`;}else{$('status').textContent=`${e}: ${state} is unavailable; see the missing-art list or unsupported enemy abilities.`;}requestAnimationFrame(render)}
$('play').onclick=()=>{playing=!playing;start=performance.now();$('play').textContent=playing?'Pause study':'Play study'};requestAnimationFrame(render);
</script></html>'''


if __name__=='__main__':build()
