"""Meaningful spend guards; simulated only, never invoke paid providers."""
import tempfile
import unittest
import json
from pathlib import Path
from common import write, week
from generate import Budget,quota_evidence
from providers import ProviderBudget, distinct_outputs,agy_preflight_unavailable
from agy_evidence import AgyEvidence


class ProviderGuardTests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory(); self.art=Path(self.tmp.name)
        write(self.art/'budget.json',{'wave_hard_cap':240,'weekly_image_cap':240,'target_images':240,'max_attempts_per_scene':3})
        write(self.art/'usage.json',{'schema':1,'stop':None,'jobs':[],'events':[]})
        write(self.art/'providers/budget.json',{'providers':{'agy':{'weekly_image_cap':150,'external_known_charges':{week():4}},'grok':{'weekly_image_cap':240}}})
        write(self.art/'providers/history.json',{'providers':{p:{'stop':None,'events':[]} for p in ['agy','grok']}})

    def tearDown(self): self.tmp.cleanup()

    def test_provider_quota_does_not_stop_other_or_refund(self):
        b=Budget(self.art);p=ProviderBudget(self.art)
        b.reserve({'id':'one','style_id':'covenant','scene':'one','provider':'agy'})
        b.update('one',{'status':'quota-stopped'})
        p.event('agy','stop','one','HTTP 429')
        self.assertFalse(p.available('agy')[0]);self.assertTrue(p.available('grok')[0])
        self.assertEqual(b.summary()['wave_reserved'],1)
        self.assertIsNone(b.load()['stop'])
        b.reserve({'id':'two','style_id':'covenant','scene':'two','provider':'grok'})
        self.assertEqual(b.summary()['wave_reserved'],2)

    def test_provider_cap_includes_known_external_probe_spend(self):
        p=ProviderBudget(self.art)
        usage={'jobs':[{'provider':'agy','week':week(),'charged_images':146}]}
        self.assertFalse(p.available('agy',usage)[0]);self.assertTrue(p.available('grok',usage)[0])

    def test_project_cap_still_spans_providers(self):
        b=Budget(self.art);v=b.load()
        v['jobs']=[{'id':'history','week':week(),'charged_images':240,'status':'generated','provider':'grok'}];b.save(v)
        with self.assertRaisesRegex(RuntimeError,'HARD_BUDGET_CAP'):
            b.reserve({'id':'agy-one','style_id':'covenant','scene':'one','provider':'agy'})

    def test_stop_survives_new_instance(self):
        ProviderBudget(self.art).event('agy','stop','x','quota exhausted')
        self.assertFalse(ProviderBudget(self.art).available('agy')[0])

    def test_payment_balance_error_is_quota_evidence_not_a_retry(self):
        value={'type':'error','message':'API error (status 402 Payment Required): Grok Build usage balance exhausted'}
        self.assertIsNotNone(quota_evidence(value))
        self.assertIsNone(quota_evidence({'arguments':{'prompt':value['message']}}))

    def test_preflight_503_is_specific_and_does_not_hide_a_started_call(self):
        output='Eligibility check failed: UNAVAILABLE (code 503): The service is currently unavailable.'
        self.assertTrue(agy_preflight_unavailable(output,[]))
        self.assertFalse(agy_preflight_unavailable(output,[{'name':'generate_image'}]))
        self.assertFalse(agy_preflight_unavailable('quota exhausted',[]))

    def test_duplicate_save_is_one_image_with_all_evidence(self):
        a=self.art/'output.png'; b=self.art/'source.png'
        a.write_bytes(b'same generated bytes'); b.write_bytes(a.read_bytes())
        chosen,evidence=distinct_outputs([b,a])
        self.assertEqual(chosen,[a]); self.assertEqual(len(evidence[0]['paths']),2)

    def test_distinct_extra_output_is_not_deduplicated(self):
        a=self.art/'output.png'; b=self.art/'second.png'
        a.write_bytes(b'first'); b.write_bytes(b'second')
        chosen,evidence=distinct_outputs([a,b])
        self.assertEqual(len(chosen),2); self.assertEqual(len(evidence),2)

    def test_agy_finds_hidden_second_call_only_in_owned_worker(self):
        brain=self.art/'brain';brain.mkdir()
        audit=AgyEvidence('exact request',brain)
        def transcript(ident,events):
            p=brain/ident/'.system_generated/logs/transcript_full.jsonl';p.parent.mkdir(parents=True)
            p.write_text('\n'.join(json.dumps(e) for e in events),encoding='utf-8')
        call={'step_index':1,'tool_calls':[{'name':'generate_image','args':{'Prompt':'"paint"'}}]}
        transcript('parent',[{'type':'USER_INPUT','content':'<USER_REQUEST>exact request</USER_REQUEST>'}])
        transcript('worker',[{'type':'SYSTEM_MESSAGE','content':'sender=parent content=paint'},call,{**call,'step_index':2}])
        transcript('other',[{'type':'USER_INPUT','content':'unrelated'},call])
        calls,_,_=audit.collect()
        self.assertEqual(len(calls),2);self.assertEqual(audit.owned,{'parent','worker'})

    def test_unresolved_project_reservation_blocks_every_provider(self):
        b=Budget(self.art);b.reserve({'id':'one','style_id':'covenant','scene':'one','provider':'agy'})
        with self.assertRaisesRegex(RuntimeError,'UNRESOLVED_RESERVATION'):
            b.reserve({'id':'two','style_id':'covenant','scene':'two','provider':'grok'})

    def test_agy_completed_artifact_must_belong_to_exact_request(self):
        brain=self.art/'brain';brain.mkdir();audit=AgyEvidence('one request',brain)
        own=brain/'owned';own.mkdir();output=own/'first.png';output.write_bytes(b'image')
        other=brain/'unrelated';other.mkdir();secret=other/'other.png';secret.write_bytes(b'other')
        log=own/'.system_generated/logs/transcript_full.jsonl';log.parent.mkdir(parents=True)
        events=[{'type':'USER_INPUT','content':'one request'},
                {'type':'GENERIC','content':f'Generated image is saved at {output}.'},
                {'type':'GENERIC','content':f'Generated image is saved at {secret}.'}]
        log.write_text('\n'.join(json.dumps(e) for e in events),encoding='utf-8')
        audit.collect()
        self.assertEqual(audit.completed_images(),[output.resolve()])


if __name__=='__main__':unittest.main()
