import { readFileSync, writeFileSync } from 'node:fs';
const directory = new URL('../../../docs/waves/W4b-evidence/', import.meta.url);
const read = name => JSON.parse(readFileSync(new URL(name, directory), 'utf8'));
const browser = read('browser.json'), census = read('oval-census.json'), core = read('core-tests.json'), game = read('game-tests.json');
if (core.numFailedTests || game.numFailedTests || browser.errors.length || browser.performance.some(p => p.minimumVisibleAcrossSamples < 100 || p.cpuP95Ms >= p.cpuBudgetMs || p.fpsFromMeanFrame < p.targetFps * (1 - p.fpsToleranceFraction))) throw Error('Cannot label failed camera/test evidence as passed');
const escape = text => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const pictures = [];
for (const h of [1080, 1440]) pictures.push(
  [`${h}p-near-clean.png`, `${h}p near · clean view`, 'Paused authored comparison: upright mage, forward ward, ground circles and two zero-damage projectiles.'],
  [`${h}p-near-scale.png`, `${h}p near · scale overlay`, 'Paused authored comparison with the live contract calculations and figure/ground rulers.'],
  [`${h}p-far-scale.png`, `${h}p far · scale overlay`, 'Same authored scene at zoom 0.8. The camera sees more ground; the figure becomes 4% of viewport height.'],
  [`${h}p-foot-depth-order.png`, `${h}p overlapping billboards`, 'Paused deliberate overlap fixture. Painter order follows interpolated ground feet, not sprite centre or texture height.'],
  [`${h}p-live-charge.png`, `${h}p live charge`, 'Ordinary roster-practice telegraph, without injected combat effects.'],
  [`${h}p-100-projectiles.png`, `${h}p projectile performance field`, '100 visible, moving, zero-damage training projectiles. The report checks every sampled frame.']
);
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>W4b camera evidence</title>
<style>body{margin:0;background:#eee9d8;color:#263a3e;font:16px/1.6 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:32px}h1{font:42px Georgia,serif;margin:8px 0}h2{font:28px Georgia,serif;margin-top:36px}a{color:#176179}p{max-width:1050px}.status{border-left:5px solid #aa453b;background:#fff7e5;padding:16px 22px}table{border-collapse:collapse;background:#fff9e9;width:100%;max-width:1000px}td,th{text-align:left;border-bottom:1px solid #ccc5b2;padding:10px 16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}figure{margin:0;background:#fff9e9;border:1px solid #c1b9a1}figure img{display:block;width:100%;height:auto}figcaption{padding:14px 18px}figcaption b{display:block}figcaption small{display:block;color:#596764}code{font-size:13px}@media(max-width:850px){main{padding:18px}.grid{grid-template-columns:1fr}table{font-size:13px}td,th{padding:7px}}</style>
<main><p>ARENA · W4b / W4c · 2026-10-02</p><h1>The open oval, at the confirmed distance</h1>
<p>55° oblique view. Near zoom 1.2; range 0.8–1.2. Upright mage height is 6% of viewport height at near. The playable arena is 192 × 144 m; each image shows only a local patch. Original procedural figures remain until A3 delivery.</p>
<p><a href="../../../art/review/sources/01-tessera-open-oval-sparse-near-a01.jpg">Owner-chosen proof</a> · <a href="../../../art/CAMERA-OK.md">Camera confirmation</a> · <a href="../W4b-camera-scale.md">Wave note</a> · <a href="../../OWNER-CHECKS.md">Owner checks</a> · <a href="../../../packages/game/README.md">Run / sprite handoff</a></p>
<div class="status"><b>Camera, scale, input and performance checks passed; owner feel remains pending.</b><br>${core.numPassedTests} core + ${game.numPassedTests} game tests, ${browser.aimChecks.length} real-pointer ground-hit cases. Broader Tiro pacing is reopened: the first two waves exceed their old median bands. No combat damage, HP, resource or target-band retuning was performed.</div>
<h2>Measured performance</h2><p>Each row has 360 uncontended headless Chromium frames with the debug overlay on and 100 visible moving projectiles throughout. CPU includes fixed-step simulation, geometry, HUD and renderer submission. GPU completion and physical input latency are not measured.</p>
<table><tr><th>Viewport</th><th>Mean fps</th><th>CPU p95</th><th>Frame p95</th><th>Minimum visible</th></tr>${browser.performance.map(p => `<tr><td>${p.viewport.width} × ${p.viewport.height}</td><td>${p.fpsFromMeanFrame.toFixed(3)}</td><td>${p.cpuP95Ms.toFixed(2)} ms</td><td>${p.frameP95Ms.toFixed(2)} ms</td><td>${p.minimumVisibleAcrossSamples}</td></tr>`).join('')}</table>
<p>${escape(browser.machine.cpu.trim())}; ${escape(browser.performance[0].gpu)}. <a href="browser.json">Complete browser report</a> · <a href="core-tests.json">Core tests</a> · <a href="game-tests.json">Game tests</a>.</p>
<h2>Native resolution screenshots</h2><p>Click any image for its full-size file. Paused authored comparisons isolate projection and scale; live and performance captures are labelled separately. Neither static images nor automated hits certify comfort in motion.</p>
<div class="grid">${pictures.map(([file, title, description]) => `<figure><a href="${file}"><img src="${file}" alt="${escape(title)}" loading="lazy"></a><figcaption><b>${escape(title)}</b><small>${escape(description)}</small></figcaption></figure>`).join('')}</div>
<h2>Tiro pacing revalidation</h2><table><tr><th>Wave</th><th>Median target</th><th>Simulated median</th><th>Result</th></tr>${census.waves.map(w => `<tr><td>${escape(w.kind)}</td><td>${w.targetDurationS.join('–')} s</td><td>${w.durationS.p50.toFixed(3)} s</td><td>${w.passed ? 'PASS' : 'FAIL'}</td></tr>`).join('')}</table>
<p>2,000 seeded fights per wave, including losses and tails; no timeouts, early Downs, invalid states or sampled replay mismatches. The command returns exit 1 for the two median failures. <a href="oval-census.json">Full final census</a> · <a href="oval-row-census.json">Earlier row-layout census</a> · <a href="competence-ladder.json">Competence / selected completion fixture</a>.</p>
<p>Additional production-browser regressions: <a href="controls/browser.json">movement, cast, ward and perfect</a> · <a href="water/browser.json">Water composition</a> · <a href="games/browser.json">four-bout lifecycle and roster</a>. <a href="games/01-tiro-soldiers.png">Live Tiro</a> · <a href="games/04-tiro-champion.png">selected fixture completion</a>.</p>
<p>Rebuild this index from reports with <code>node packages/game/scripts/camera-gallery.mjs</code>. Owner verdict and G1 remain open.</p></main></html>`;
writeFileSync(new URL('index.html', directory), html, 'utf8');
console.log('W4b evidence gallery rebuilt from browser, test and census reports.');
