import { readFileSync, writeFileSync } from 'node:fs';
const root='docs/waves/W7-evidence';
const census=JSON.parse(readFileSync(`${root}/integrated-census.json`,'utf8'));
const soak=JSON.parse(readFileSync(`${root}/soak.json`,'utf8'));
const screens=[['character-pick','Water and three camp allies'],['camp-map','Accepted camp map'],['controls','Pause, settings and controls'],['night-knowing','Night listening act'],['knowing-parley','Knowing-gated Parley'],['day-6-trial','First Tent Trial'],['day-7-games','First Tiro encounter'],['day-7-result','First Games result'],['day-8-board','Consequences at the next morning'],['day-13-trial','Second Tent Trial'],['day-14-games','Second Games'],['day-14-result','Missio by ordinary damage'],['day-15-board','Second morning board'],['two-weeks','Chapter completed']];
const groups=[1080,1440].map(h=>`<section class="screens" data-height="${h}" ${h===1440?'hidden':''}>${screens.map(([name,title])=>`<article><h2>${title}</h2><a href="screens/${h}-${name}.png"><img loading="lazy" src="screens/${h}-${name}.png" alt="${title}, ${h}p production browser screenshot"></a><p>${h===1080?'1920 x 1080':'2560 x 1440'} viewport. Open the image for native size.</p></article>`).join('')}</section>`).join('');
writeFileSync(`${root}/index.html`,`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mage Arena W7 evidence</title><style>body{margin:0;background:#142c35;color:#f5e6c3;font:16px/1.55 system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:32px}h1{font:42px Georgia,serif;margin:0}h2{font:25px Georgia,serif}a{color:#87deea}p{max-width:1000px}nav{display:flex;gap:12px;margin:24px 0}button{padding:12px 24px;background:#f5e6c3;color:#142c35;border:2px solid #c49c50;cursor:pointer}button[aria-pressed=true]{background:#247589;color:white}.screens{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.screens[hidden]{display:none}article{border:1px solid #a68549;padding:16px}img{width:100%;height:auto}table{border-collapse:collapse}td,th{text-align:left;padding:8px 18px;border-bottom:1px solid #a68549}small{color:#c8bca0}.notice{border-left:4px solid #db8854;padding-left:18px}@media(max-width:800px){.screens{grid-template-columns:1fr}}</style><main>
<small>INTEGRATION / W7 / WINDOWS PRODUCTION BROWSER</small><h1>Two weeks beneath the collar</h1>
<p class="notice">Measured browser controls and screenshots; combat outcomes use a disclosed scripted policy. Human feel and G1 remain open until the owner plays. All figures are procedural placeholders; no discarded A2/A3 art is loaded.</p>
<p><a href="../../OWNER-CHECKS.md">Run and owner checks</a> · <a href="../W7-execution.md">Design decisions and failures retained</a> · <a href="../W7-report.md">Gate report</a></p>
<h2>Original duration bands, unchanged</h2><table><tr><th>Wave</th><th>Band</th><th>2,000-fight median</th><th>Gate</th></tr>${census.waves.map((w:{kind:string;targetDurationS:number[];durationS:{p50:number};passed:boolean})=>`<tr><td>${w.kind}</td><td>${w.targetDurationS.join('–')} s</td><td>${w.durationS.p50.toFixed(2)} s</td><td>${w.passed?'PASS':'FAIL'}</td></tr>`).join('')}</table>
<p>Approach, spacing and AI changes only. No health, damage, camera or target-band reduction. <a href="integrated-census.json">Full census</a> · <a href="data-authorities.json">Pinned-source comparison</a> · <a href="replay-save.json">Exact deterministic save bytes</a> · <a href="save-tests.json">Save matrix</a></p>
<p>Soak: ${soak.passed?'PASS':'pending'}; ${(soak.elapsedMs/60000).toFixed(2)} minutes, ${soak.cycles} browser cycles, ${soak.simulationDays} simulated season days, ${soak.paidCallsAdded} model calls. <a href="soak.json">Raw measurements</a> · <a href="scenes-browser.json">Composer cancellation and arena remounts</a></p>
<nav aria-label="Screenshot resolution"><button aria-pressed="true" data-show="1080">1080p</button><button aria-pressed="false" data-show="1440">1440p</button></nav>${groups}
<h2>Camera and art boundaries</h2><p><a href="camera/browser.json">32 native pointer hits, depth order, both zooms and 100 visible moving projectiles</a> · <a href="camp/browser.json">Camp and missing-asset fallback</a> · <a href="parley/browser.json">Offline typed approach and authored card</a> · <a href="director-browser.json">Validated Director night and morning board</a> · <a href="director-ledger.json">Seven of twenty subscription reservations</a></p>
<p><a href="camera/1080p-near-clean.png"><img loading="lazy" src="camera/1080p-near-clean.png" alt="Confirmed near oblique arena camera with procedural figures"></a></p>
<p>Camera comparison images are deliberately paused fixtures. Frame-rate measurements are headless Chromium scheduling and CPU submission, not physical input latency. Owner judgments remain separate.</p></main><script>for(const button of document.querySelectorAll('[data-show]'))button.onclick=()=>{for(const section of document.querySelectorAll('[data-height]'))section.hidden=section.dataset.height!==button.dataset.show;for(const b of document.querySelectorAll('[data-show]'))b.setAttribute('aria-pressed',String(b===button));};</script></html>`,'utf8');
