"""Build both portable HTML reports from the actual ledger, never from assumed outputs."""
import html, json, re
from collections import defaultdict
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
AUDIO = ROOT / 'docs/audio'
plan = json.loads((ROOT / 'tools/audio/audition-plan.json').read_text(encoding='utf-8'))['samples']
ledger = [json.loads(x) for x in (ROOT / 'tools/audio/ledger.jsonl').read_text(encoding='utf-8').splitlines() if x]
measure = {m['id']:m for m in json.loads((AUDIO / 'evidence/measurements.json').read_text(encoding='utf-8'))}
actual = {Path(e['out']).stem:e for e in ledger}
esc = lambda x: html.escape(str(x), quote=True)
slug = lambda x: re.sub('[^a-z0-9]+', '-', x.lower()).strip('-')
categories = list(dict.fromkeys(s['category'] for s in plan))
def header(title, subtitle, proof=False):
    prefix = '' if proof else '../../'
    link = '<a href="audition/r1/index.html">Direction triage</a>' if proof else '<a href="../../PROOF-REPORT.html">Investment evidence</a>'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} · Mage Arena</title><link rel="stylesheet" href="{prefix}report.css"></head><body><main><header><div class="eyebrow">Mage Arena / Audio / AU1 / 02 October 2026</div><h1>{esc(title)}</h1><p>{subtitle}</p><div class="toolbar">{link}<a href="{prefix}AUDIO-BIBLE.md">Audio philosophy</a><label>Theme <select id="theme"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><input id="matched" type="checkbox" checked> Measured playback trim</label></div></header>'''
notice = '''<div class="notice"><strong>Stopped after 2 proof samples; 38 planned samples were not generated.</strong><br>The music response omitted its billing header, triggering the local billing-uncertainty latch. No quota or rate-limit error occurred; the 12,000-credit cap was not reached. This is incomplete audition evidence, not a verdict on the Starter plan. Generation remains stopped.</div>'''
def player(s, proof=False):
    e, m = actual[s['id']], measure[s['id']]
    file = ('audition/r1/' if proof else '') + Path(e['out']).name
    cost = f"{e['measuredCredits']:g} credits measured" if e['measuredCredits'] is not None else 'Actual credits unresolved; 1,200 reserved'
    return f'''<div class="sample"><h4>{esc(s['id'])}</h4><audio id="audio-{esc(s['id'])}" controls preload="none" src="{esc(file)}" data-gain="{m['auditionGainDb']}" aria-label="{esc(s['id'])}"></audio><small>{m['decodedSeconds']:.3f} s decoded · {cost}<br>Raw {m['integratedLufs']} LUFS-I / {m['truePeakDbTP']:+.1f} dBTP · playback trim {m['auditionGainDb']:+.1f} dB</small><details><summary>Prompt and provenance</summary><p>{esc(e['text'])}</p><p>Requested {e['seconds']} s; model {esc(e['model'])}; raw provider output.</p><a href="{esc(file)}.json">Asset sidecar</a></details>{f'<button type="button" data-loop-target="audio-{esc(s["id"])}" aria-pressed="false">Repeat for seam listening</button>' if s['kind']=='music' else ''}</div>'''
def footer(proof=False):
    prefix = '' if proof else '../../'
    return f'''<footer><p>All sound directions are proposals. No owner choices have been inferred. Raw samples are preserved; gain matching changes playback only. No service calls occur from this report.</p><p><a href="{prefix}evidence/LOUDNESS.md">Loudness evidence</a> · <a href="{prefix}evidence/COST-MODEL.md">Cost assumptions and sources</a></p><p id="status" class="status" role="status" aria-live="polite"></p></footer></main><script src="{prefix}report.js"></script></body></html>'''
def loudness_table():
    rows = ''.join(f'<tr><td>{esc(m["id"])}</td><td>{m["decodedSeconds"]:.3f}</td><td>{m["integratedLufs"]}</td><td>{m["truePeakDbTP"]}</td><td>{m["loudnessRangeLu"]}</td><td>{m["auditionGainDb"]}</td></tr>' for m in measure.values())
    return '<div class="table-wrap"><table><thead><tr><th>Sample</th><th>Seconds</th><th>LUFS-I</th><th>dBTP</th><th>LRA LU</th><th>Trim dB</th></tr></thead><tbody>'+rows+'</tbody></table></div>'
r1 = header('Pressure, matter, returning light', 'Round 1 direction triage. Listen to the two available proofs, mark a direction, and export notes for CHOICES.md. Unrendered directions cannot be compared yet.') + notice
r1 += '<nav aria-label="Themes">'+''.join(f'<a href="#{slug(c)}">{esc(c)}</a>' for c in categories)+'</nav>'
r1 += '<p class="muted">The fire cast is trimmed to −20 LUFS and arena music to −24 LUFS for this report. Start at a comfortable volume. These are review levels, not the proposed in-game mix. Only one player runs at once.</p>'
for c in categories:
    group = [s for s in plan if s['category']==c]
    r1 += f'<section id="{slug(c)}"><h2>{esc(c)}</h2><div class="cards">'
    dirs = defaultdict(list)
    for s in group: dirs[s['direction']].append(s)
    for direction, samples in dirs.items():
        rendered = [s for s in samples if s['id'] in actual]
        if not rendered: continue
        did = slug(c+' '+direction)
        r1 += f'<article class="card" data-direction="{did}" data-label="{esc(c+" / "+direction)}" data-samples="{esc(", ".join(s["id"] for s in rendered))}"><div class="tag">Proposal · {esc(c)}</div><h3>{esc(direction)}</h3><p>{esc(samples[0]["philosophy"])}</p>'
        r1 += ''.join(player(s) for s in rendered)
        r1 += f'<fieldset><legend>Direction choice</legend><div class="picks">'+''.join(f'<label><input type="radio" name="{did}" value="{v}"> {v.title()}</label>' for v in ['keep','maybe','reject'])+'</div></fieldset>'
        r1 += f'<label for="note-{did}">Optional owner note</label><textarea id="note-{did}" placeholder="What works, what should change?"></textarea></article>'
    r1 += '</div>'
    missing = [s for s in group if s['id'] not in actual]
    if missing: r1 += '<div class="empty"><strong>Not generated after the latch:</strong> '+esc('; '.join(dict.fromkeys(s['direction'] for s in missing)))+f' ({len(missing)} samples). No choice is preselected.</div>'
    r1 += '</section>'
r1 += '''<section class="export"><h2>Take your choices with you</h2><p>Choices stay in localStorage for this browser and file path. Copy the Markdown before moving folders or switching browsers. Paste it into <a href="../../CHOICES.md">CHOICES.md</a>; keep means keep exploring the direction, not accept the raw asset for production.</p><div class="toolbar"><button id="copy" type="button">Copy Markdown choices</button><button id="refresh-export" type="button">Preview Markdown</button></div><label for="export">Markdown export</label><textarea id="export" readonly></textarea></section><section><h2>Measured raw loudness</h2>'''+loudness_table()+'</section>'+footer()
(AUDIO / 'audition/r1/index.html').write_text(r1, encoding='utf-8')

p = header('What this audition proves', 'Investment evidence: a complete catalogue of everything actually generated, with cost uncertainty, technical quality checks and the missing comparisons stated plainly.', True)+notice
p += '<div class="facts"><div class="metric"><strong>2 / 40</strong>planned samples rendered</div><div class="metric"><strong>20</strong>credits exactly attributed</div><div class="metric"><strong>1,220</strong>conservative debit / 12,000 cap</div><div class="metric"><strong>42,061</strong>account credits at generation stop</div></div>'
p += '<nav aria-label="Proof sections"><a href="#catalogue">Catalogue</a><a href="#cost">Cost model</a><a href="#quality">Quality</a><a href="#seams">Loop checks</a><a href="#loudness">Loudness</a><a href="#production">Production forecast</a><a href="#investment">Before investing</a><a href="#matrix">Full comparison matrix</a></nav>'
p += '<section id="catalogue"><h2>Everything generated</h2><p>Every original MP3 appears below. There are no discarded hidden takes, derived paid samples, production assets or generated voice lines.</p>'
for c in categories:
    found = [s for s in plan if s['category']==c and s['id'] in actual]
    p += f'<h3>{esc(c)}</h3>'
    if not found: p += '<p class="empty">0 samples · 0 credits · not measured.</p>'; continue
    measured_sum = sum(actual[s['id']]['measuredCredits'] or 0 for s in found)
    debit_sum = sum(actual[s['id']]['chargedCredits'] for s in found)
    p += f'<p>{len(found)} sample · exactly attributed: {measured_sum} credits; conservative budget debit: {debit_sum} credits.</p><div class="cards">'
    for s in found: p += '<article class="card"><h3>'+esc(s['direction'])+'</h3><p>'+esc(s['philosophy'])+'</p>'+player(s, True)+'</article>'
    p += '</div>'
p += '</section>'
p += '''<section id="cost"><h2>Cost model and the stopping point</h2><div class="table-wrap"><table><thead><tr><th>Proof</th><th>Measured evidence</th><th>Cost model</th></tr></thead><tbody><tr><td>2 s SFX</td><td>character-cost header: 20</td><td>10 credits / requested second; one sample, no minimum inferred</td></tr><tr><td>20 s music</td><td>No billing header. Shared balance fell by 620.</td><td>600 / 20 = 30 credits/s is an inference if the other 20 are delayed SFX billing. Exact music cost unresolved.</td></tr><tr><td>Voice</td><td>Not called after latch</td><td>Credits per character not measured; original planning bound 1/character</td></tr><tr><td>Total</td><td>20 exact; 620 account change across the two-call interval</td><td>1,220 conservative budget debit: 20 measured + 1,200 unresolved reservation</td></tr></tbody></table></div><p><strong>10,780 credits of cap capacity remain unused and locked.</strong> The 8,000 shared reserve was preserved. The account read 42,681 immediately before the SFX and 42,061 at 19:14:19 UTC after music; reset is 2026-10-04 19:31:41 UTC. Other projects continue to spend on the same account. An earlier read was 42,721, already below the owner's older 43,319 snapshot.</p><p>The tool deliberately persisted a reservation before each billable POST. It kept the music's 1,200-credit upper bound because billing attribution failed. This local latch is stricter than the requested quota/rate-limit latch. It stopped the audition early; <strong>it is not a provider plan limit and not evidence that more expensive access is necessary.</strong> No latch was cleared and no further generation was attempted.</p><p>The SFX's immediate balance change was zero; it was still billed. Read-only analytics exposed routes and timestamps but no costs, and showed another music call shortly after this tool stopped. Public API and Creative price pages differ from these account measurements. See the <a href="evidence/COST-MODEL.md">complete arithmetic and source record</a>.</p></section>'''
p += '''<section id="quality"><h2>Quality self-assessment</h2><p class="readiness">Technical assessment only. I cannot claim a listening judgement from ffmpeg measurements. Owner feel, exact instrumentation, absence of unwanted content and family identity remain unjudged.</p><div class="table-wrap"><table><thead><tr><th>Category</th><th>What is potentially useful</th><th>What is not established / usable as delivered</th></tr></thead><tbody><tr><td>One-shot SFX</td><td>The fire cast decodes to exactly 2.000 s, begins immediately, and falls below the activity threshold after 1.31 s. It is a plausible editable one-shot candidate.</td><td>Raw true peak is +0.8 dBTP; 56 decoded channel samples exceed full scale. It needs gain/peak treatment. No listening conformance or alternate elemental family test occurred.</td></tr><tr><td>Music</td><td>A complete 20.062 s stereo sketch was delivered, with no decoded samples above full scale. Useful for hearing one stylistic proposal.</td><td>It is a full mix, not four independent adaptive layers. Requested 96 BPM and section shapes are unverified. Direct repeat fails the edge-level screen. No alternate directions exist yet.</td></tr><tr><td>Camp beds / ambience</td><td>Original briefs and time/place philosophy are written.</td><td>Zero audio generated; loop quality, environmental credibility and fatigue cannot be rated.</td></tr><tr><td>UI / absorb / hits / crowd</td><td>Event grammar and comparison briefs are written.</td><td>Zero generated samples; event distinction, repetition and family coherence not measured.</td></tr><tr><td>Voice</td><td>Three stock candidate voices were found; identical line is prepared.</td><td>No speech generation, no measured cost, pronunciation, pacing or acting evidence.</td></tr></tbody></table></div><p>ElevenLabs demonstrated delivery of a short one-shot and a music sketch in this run. It did not demonstrate finished loops or adaptive assets. That is a limitation of this evidence and these requests, not proof that the service cannot produce them. A broad claim that its SFX are strong or its music weak would exceed two unjudged samples.</p><p><strong>Consistency:</strong> one cast and one score cannot establish a family. Test at least paired A/B casts for all four elements, normal versus perfect absorb pairs, and all five controls in each UI family. Consistent prompt vocabulary is authorship, not measured sonic consistency.</p></section>'''
m = measure['arena-A-hide-and-iron']['seam']
p += f'''<section id="seams"><h2>Loop and seam checks</h2><p>No camp bed was generated. The arena sketch was requested as a style sketch; the following direct-repeat test probes whether it could already serve as a bed. It does not certify a music loop.</p><div class="table-wrap"><table><thead><tr><th>Check</th><th>Result</th><th>Meaning</th></tr></thead><tbody><tr><td>Three decoded PCM repeats, two joins</td><td>Both sample jumps {m['boundaryJumpDbFS']} dBFS</td><td>Passes the authored ≤ −60 dBFS click screen only</td></tr><tr><td>0.5 s edge RMS</td><td>Head {m['headHalfSecondRmsDbFS']}, tail {m['tailHalfSecondRmsDbFS']} dBFS; difference {m['edgeLevelDifferenceDb']} dB</td><td>Fails authored ≤ 3 dB level-step screen</td></tr><tr><td>Edge spectral centroid</td><td>Head {m['headCentroidHz']} Hz; tail {m['tailCentroidHz']} Hz</td><td>Substantial content change; diagnostic, not a perceptual threshold</td></tr><tr><td>Tempo, downbeat, tail and harmony continuity</td><td>Not measured</td><td>Needed before loop authoring; no silent “pass”</td></tr><tr><td>Camp day/dusk/night and place beds</td><td>Not generated</td><td>No seam claim possible</td></tr></tbody></table></div><p>Use the music player's repeat control to listen over three passes. Native MP3 browser looping may add a gap, so a production loop requires measured PCM boundaries and an actual runtime decode test. No crossfade repair was applied to hide the raw evidence. A tiny endpoint jump does not remove the 5.21 dB content step.</p></section>'''
p += '<section id="loudness"><h2>Loudness: every generated sample</h2><p>ffmpeg ebur128 with true-peak mode, measured on raw provider files. The meter prints its oversampled true-peak result as “dBFS”; this table labels it dBTP. Browser trims preserve original files and do not master them.</p>'+loudness_table()+'<p><a href="evidence/measurements.json">Full measurements, decoded sample counts and envelopes</a> · <a href="evidence/fire-A-wounded-matter.ebur128.txt">Fire meter output</a> · <a href="evidence/arena-A-hide-and-iron.ebur128.txt">Music meter output</a></p></section>'
p += '''<section id="production"><h2>What a full set could cost</h2><p><strong>Conditional forecast, not a quote.</strong> Assume 150 SFX × 2 s, 20 UI × 1 s, 8 ambiences × 30 s, and 12 music tracks × 90 s × 4 independently authored adaptive layers. The last item is 4,320 generated seconds. This run did not demonstrate independently usable layers.</p><div class="table-wrap"><table><thead><tr><th>Category</th><th>At observed SFX / inferred music rate</th><th>At conservative guard bounds</th></tr></thead><tbody><tr><td>150 SFX</td><td>3,000 credits</td><td>15,000</td></tr><tr><td>20 UI</td><td>200</td><td>2,000</td></tr><tr><td>8 ambiences</td><td>2,400</td><td>9,600</td></tr><tr><td>12 × 4 music layers</td><td>129,600</td><td>259,200</td></tr><tr><td>Total, one take</td><td>135,200</td><td>285,800</td></tr><tr><td>With 50% generation rework</td><td>202,800</td><td>428,700</td></tr></tbody></table></div><p>At the public Creative allowances of Starter 30k credits / $6 monthly and Creator 121k / $22 monthly, reserving 8k once and assigning no credits to sister projects:</p><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Starter</th><th>Creator, next tier</th></tr></thead><tbody><tr><td>135,200</td><td>5 months / $30</td><td>2 months / $44</td></tr><tr><td>202,800</td><td>8 months / $48</td><td>2 months / $44</td></tr><tr><td>285,800 conservative</td><td>10 months / $60</td><td>3 months / $66</td></tr><tr><td>428,700 conservative + rework</td><td>15 months / $90</td><td>4 months / $88</td></tr></tbody></table></div><p>Whole-month scenarios use ceil((required + 8,000) / monthly credits). They exclude taxes, introductory offers, extra-credit purchases and post-production labour. The measured 90k account limit does not establish a recurring 90k monthly entitlement. Rollover constraints and shared spending can alter the timetable. Sources: <a href="https://elevenlabs.io/pricing">Creative pricing</a> and <a href="https://elevenlabs.io/pricing/api">API pricing</a>, retrieved 2026-10-02. The API page describes dollar metering; confirm what a migration would do to this account before treating any credit scenario as a purchase quote.</p><p>A lean full-mix version (one 90 s mix per track) is 38,000 conditional credits, or 57,000 with 50% rework, but it does not provide four adaptive layers. More generations also do not guarantee a usable loop or better dramatic identity.</p></section>'''
p += '''<section id="investment"><h2>Before investing: questions for the comparison</h2><p><strong>Recommendation from the available evidence:</strong> resolve music billing attribution before another paid batch. This run is too small to justify an upgrade on quality grounds. Review the two proofs, then compare identical tasks; do not buy a larger plan merely because this local tool stopped.</p><ol><li>Does the next ElevenLabs tier change the capabilities needed (export format, independent composition layers, loop control), or mainly increase allowance? Can exact per-request music costs be retrieved on this shared account?</li><li>Which Google audio products are actually available through the owner's Ultra plan, and which require separately billed cloud access? Are SFX, instrumental music, narration, stems and file export all supported? No entitlement is assumed.</li><li>Can both providers meet the same 2 s cast envelope, distinguish a normal and perfect absorb, and maintain all five UI sounds in one family? Repeat exactly the authored matrix below with the same texts and durations, blind labels, matched playback levels and equal attempt limits.</li><li>Can a 96 BPM arena bed maintain a measurable grid, repeat three times without a content seam and supply aligned layers whose subsets stand alone? Can day/dusk/night ambience remain featureless under repetition?</li><li>What is the cost per accepted game-ready take after retakes, loop editing, mastering and export? Are usage rights and attribution requirements compatible with the intended game distribution?</li></ol><p>Record exact request duration, decoded duration, prompt, model, cost, latency and failure status for each provider. Unsupported categories stay marked unsupported. Use the same short narrator line and comparable calm stock registers; no voice cloning is required. No Google service was called.</p></section>'''
p += '<section id="matrix"><h2>The same 40-sample comparison list</h2><p>Authored briefs only; 38 are not generated. This is an AU1 scope record and proposed fair-comparison list, not a production batch or authorization to resume.</p><div class="table-wrap"><table><thead><tr><th>Sample / category</th><th>Length</th><th>Status / original prompt</th></tr></thead><tbody>'
for s in plan: p += f'<tr><td>{esc(s["id"])}<br><small>{esc(s["category"])}</small></td><td>{str(s["seconds"])+" s" if s["seconds"] else str(len(s["prompt"]))+" chars"}</td><td>{"Generated proof" if s["id"] in actual else "Not generated — latch"}<details><summary>Brief</summary><p>{esc(s["philosophy"])}</p><p>{esc(s["prompt"])}</p></details></td></tr>'
p += '</tbody></table></div></section>'+footer(True)
(AUDIO / 'PROOF-REPORT.html').write_text(p, encoding='utf-8')
print(f'Built both reports from {len(actual)} actual samples; {len(plan)-len(actual)} explicit gaps.')
